/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 output.glb 
*/

import React, { useRef, useLayoutEffect, useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import gsap from "gsap";

export function Model(props) {
  const { nodes, materials } = useGLTF("/portfolio/model_3d/output.glb");

  const modelRef = useRef();
  const { camera, scene } = useThree();
  const mousePosition = useRef({ x: 0, y: 0 });
  const targetRotation = useRef({ x: 0, y: 0 });

  // Optimize materials
  useMemo(() => {
    if (materials["Material.002"]) {
      materials["Material.002"].needsUpdate = false;
    }
    if (materials["Material.001"]) {
      materials["Material.001"].needsUpdate = false;
    }
  }, [materials]);

  // Track mouse movement with throttling
  useLayoutEffect(() => {
    let rafId;
    const handleMouseMove = (event) => {
      if (rafId) return;
      
      rafId = requestAnimationFrame(() => {
        mousePosition.current = {
          x: (event.clientX / window.innerWidth) * 2 - 1,
          y: -(event.clientY / window.innerHeight) * 2 + 1,
        };
        rafId = null;
      });
    };

    window.addEventListener('mousemove', handleMouseMove, { passive: true });
    return () => {
      window.removeEventListener('mousemove', handleMouseMove);
      if (rafId) cancelAnimationFrame(rafId);
    };
  }, []);

  // Optimized rotation with lerp
  useFrame(() => {
    if (modelRef.current) {
      targetRotation.current.y = mousePosition.current.x * 0.5;
      targetRotation.current.x = mousePosition.current.y * 0.3;
      
      modelRef.current.rotation.y += (targetRotation.current.y - modelRef.current.rotation.y) * 0.05;
      modelRef.current.rotation.x += (targetRotation.current.x - modelRef.current.rotation.x) * 0.05;
    }
  });
  // GSAP ScrollTrigger animations
  useLayoutEffect(() => {
    const timeline = gsap.timeline();
    
    const scrollTriggerConfig = {
      scrub: 1,
      immediateRender: false,
      lazy: false,
    };

    timeline
      .to(camera.position, {
        x: -4,
        y: -28,
        z: 100,
        ease: "power1.inOut",
        scrollTrigger: {
          ...scrollTriggerConfig,
          trigger: ".education-sec",
          start: "top bottom",
          end: "top top",
        },
      })
      .to(scene.position, {
        x: -80,
        y: -40,
        z: 15,
        ease: "power1.inOut",
        scrollTrigger: {
          ...scrollTriggerConfig,
          trigger: ".education-sec",
          start: "top bottom",
          end: "top top",
        },
      })
      .to(scene.scale, {
        x: 0.25,
        y: 0.25,
        z: 0.25,
        ease: "power1.inOut",
        scrollTrigger: {
          ...scrollTriggerConfig,
          trigger: ".education-sec",
          start: "top bottom",
          end: "top top",
        },
      })
      .to(scene.rotation, {
        x: 2,
        y: 2,
        z: 2,
        ease: "power1.inOut",
        scrollTrigger: {
          ...scrollTriggerConfig,
          trigger: ".education-sec",
          start: "top bottom",
          end: "top top",
        },
      })
      .to(".canvas", {
        background: "#fff",
        scrollTrigger: {
          ...scrollTriggerConfig,
          trigger: ".education-sec",
          start: "top bottom",
          end: "top 20%",
        },
      })
      .to(".header", {
        background: "#000177",
        scrollTrigger: {
          ...scrollTriggerConfig,
          trigger: ".education-sec",
          start: "top bottom",
          end: "top top",
        },
      })
      .to(scene.position, {
        x: 70,
        y: -40,
        z: 15,
        ease: "power1.inOut",
        scrollTrigger: {
          ...scrollTriggerConfig,
          trigger: ".techstack",
          start: "top bottom",
          end: "top top",
        },
      })
      .to(scene.rotation, {
        x: 5,
        y: 6,
        z: 4,
        ease: "power1.inOut",
        scrollTrigger: {
          ...scrollTriggerConfig,
          trigger: ".techstack",
          start: "top bottom",
          end: "top top",
        },
      });

    return () => {
      timeline.kill();
    };
  }, [camera, scene]);
  return (
    <group {...props} dispose={null} ref={modelRef}>
      <group rotation={[-0.984, 1.373, 0.975]} scale={33.994}>
        <mesh
          geometry={nodes.Sphere040.geometry}
          material={materials["Material.002"]}
          castShadow={false}
          receiveShadow={false}
        />
        <mesh
          geometry={nodes.Sphere040_1.geometry}
          material={materials["Material.001"]}
          castShadow={false}
          receiveShadow={false}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  "/portfolio/model_3d/output.glb"
);
